In [2]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
randint = torch.randint(-100,100, (6,))
randint

tensor([ 52,  62, -25, -19,  43,  79])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
# matrix of zeros
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# matrix of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
# empty matix
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(-10, 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [12]:
start_time = time.time()

# matrix operations

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time

print(f"{elapsed_time:.8f}")

0.00008512


In [13]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# speed of gpu
start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
gpu_elapsed_time = end_time - start_time
print("gpu time is")
print(f"{gpu_elapsed_time:.8f}")

# speed of cpu
start_time = time.time()
rand = np_rand1 * np_rand2
end_time = time.time()
cpu_elapsed_time = end_time - start_time
print("cpu time is")
print(f"{cpu_elapsed_time:.8f}")




gpu time is
0.04102945
cpu time is
0.02857971


In [14]:
%%time
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# records execution time taken to execute cell

0.00002980
CPU times: total: 0 ns
Wall time: 96.3 μs


In [15]:
# define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10%/0.1 => 0, 90%/0.9 => 1. each probability points to the index of the probability in the tensor
# draw 5 samples from the multinomial distribution

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
# cat = concatenate which means to combine the matrix
tensor= torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
#fills array with the exponent
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
#converts array of exponents to values
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
#transpose(which index, which position to swap
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear =nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([9.5005, 1.1078, 7.1951], grad_fn=<SqueezeBackward4>)


In [24]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [25]:
import torch.nn as nn

# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer 
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4,100) where 4 is the number of inputs and 100 is the dimensionality of the embedded vectors

print(embedded_output.shape)


torch.Size([4, 100])


In [26]:
# matrix multiplication & dot product
a = torch.tensor([[1, 2],[3, 4],[5, 6]])
b = torch.tensor([[7, 8, 9],[10, 11, 12]])

print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [27]:
# to multiply ints with floats have to add the .float() to the int
int_64 = torch.randint(1, (3,2)).float()
#type int 64

float_32 = torch.rand(2,3)
#type float 32

result = torch.matmul(int_64, float_32)

print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
